language: node_js
node_js:
  - "6.5.0"
before_script:
  - npm install babel-plugin-transform-react-jsx react-dom style-loader css-loader node-sass sass-loader react babel-loader babel-core babel-preset-es2015
  - npm install electron -g
script: npm run build
